CREATE TABLE polls ( 
	idpoll INTEGER PRIMARY KEY AUTOINCREMENT,
	question NVARCHAR2(20) NOT NULL,
	answers NVARCHAR2(20) NOT NULL
);

CREATE TABLE questions(
	idquestion INTEGER PRIMARY KEY AUTOINCREMENT,
	content NVARCHAR2(40) NOT NULL
);

CREATE TABLE answers(
	idanswer INTEGER PRIMARY KEY AUTOINCREMENT,
	content NVARCHAR2(30) NOT NULL
);