DROP TABLE IF EXISTS Polls;
DROP TABLE IF EXISTS Questions;
DROP TABLE IF EXISTS AnswerUser;
DROP TABLE IF EXISTS Answers;

CREATE TABLE Polls ( 
	idPoll INTEGER PRIMARY KEY AUTOINCREMENT,
	image NVARCHAR2(80) NOT NULL,
	question NVARCHAR2(20) NOT NULL,
	answers NVARCHAR2(20) NOT NULL
);

CREATE TABLE Questions(
	idQuestion INTEGER PRIMARY KEY AUTOINCREMENT,
	idPoll INTEGER REFERENCES polls(idpoll),
	content NVARCHAR2(40) NOT NULL
);

CREATE TABLE  AnswerUser(
	idAnswerUser INTEGER PRIMARY KEY AUTOINCREMENT,
	idPoll INTEGER REFERENCES polls(idpoll),
	idAnswer INTEGER REFERENCES Answers(idAnswer),
	idQuestion INTEGER REFERENCES Questions(idQuestion)
);

CREATE TABLE Answers(
	idAnswer INTEGER PRIMARY KEY AUTOINCREMENT,
	isAnswerUser INTEGER REFERENCES AnswerUser(idAnswerUser)
	content NVARCHAR2(30) NOT NULL
);



